// This file is automatically generated. Do not modify it manually.

const manifest = JSON.parse(`
{
    "id": "business.silly.spongebob",
    "name": "Spongebob Text Plugin",
    "description": "stOP MoCkinG mE",
    "version": "0.1.0",
    "min_server_version": "5.12.0",
    "server": {
        "executables": {
            "linux-amd64": "server/dist/plugin-linux-amd64"
        },
        "executable": ""
    },
    "webapp": {
        "bundle_path": "webapp/dist/main.js"
    },
    "settings_schema": {
        "header": "",
        "footer": "",
        "settings": []
    }
}
`);

export default manifest;
export const id = manifest.id;
export const version = manifest.version;
